In [1]:
import pandas as pd
heart = pd.read_csv('/content/heart.csv')

In [2]:
heart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64
 2   creatinine_phosphokinase  299 non-null    int64
 3   diabetes                  299 non-null    int64
 4   ejection_fraction         299 non-null    int64
 5   high_blood_pressure       299 non-null    int64
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64
 9   sex                       299 non-null    int64
 10  smoking                   299 non-null    int64
 11  time                      299 non-null    int64
 12  DEATH_EVENT               299 non-null    int64
dtypes: float64(3), int64(10)
memory usage: 30.5 KB

In [3]:
heart.head(10)

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1
5,90.0,1,47,0,40,1,204000.00,2.1,132,1,1,8,1
6,75.0,1,246,0,15,0,127000.00,1.2,137,1,0,10,1
7,60.0,1,315,1,60,0,454000.00,1.1,131,1,1,10,1
8,65.0,0,157,0,65,0,263358.03,1.5,138,0,0,10,1
9,80.0,1,123,0,35,1,388000.00,9.4,133,1,1,10,1

In [4]:
heart.drop('age',axis=1, inplace=True)

In [5]:
heart.head()

,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [6]:
#memisakhan atribut dengan label dimana x itu atribut dan y itu label
X = heart[['anaemia','creatinine_phosphokinase','diabetes','ejection_fraction','high_blood_pressure','platelets','serum_creatinine','serum_sodium','sex','smoking','time']]
y = heart['DEATH_EVENT']


#membagi dataset menjadi data latih dan data uji
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.1, random_state=123)

In [12]:
from sklearn.ensemble import RandomForestClassifier

# Membuat model Random Forest
forest_model = RandomForestClassifier()

# Melatih model menggunakan data latih dengan fungsi fit
forest_model = forest_model.fit(X_train, y_train)

In [13]:
from sklearn.metrics import accuracy_score

# Menggunakan model Random Forest untuk membuat prediksi
y_pred = forest_model.predict(X_test)

# Menghitung akurasi
accuracy = round(accuracy_score(y_test, y_pred), 3)

print('Accuracy:', accuracy)

Accuracy: 0.867

In [16]:
# Prediksi menggunakan model Random Forest
prediction = forest_model.predict([[0,582,0,2,1,265,1.9,130,1,0,4]])

print(prediction[0])

1

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [19]:
prediction = forest_model.predict([[1,160,1,20,0,327,2.7,116,0,0,8]])

print(prediction[0])

1

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [21]:
# Melihat class names dari model Random Forest
print(forest_model.classes_)

[0 1]

In [22]:
from sklearn.tree import export_graphviz

# Pilih salah satu pohon dari model Random Forest
tree = forest_model.estimators_[0]

# Menentukan nama kelas sesuai dengan yang digunakan dalam model
class_names = [str(cls) for cls in forest_model.classes_]

export_graphviz(
    tree,
    out_file="heart_random_forest.dot",
    feature_names=['anaemia','reatinine_phosphokinase','diabetes','ejection_fraction','high_blood_pressure','platelets','serum_creatinine','serum_sodium','sex','smoking','time'],
    class_names=class_names,
    rounded=True,
    filled=True
)